### ISSUE TITLE
Broken SSR support since >2.0.1

### ISSUE THREAD

**Issue by mikerogerz** [promosis/vue-programmatic-invisible-google-recaptcha#1]
```
var HEAD = document.head || document.getElementsByTagName('head')[0];
^ ReferenceError: document is not defined at /node_modules/vue-programmatic-invisible-google-recaptcha/dist/vue-programmatic-invisible-google-recaptcha.umd.js:204:16
```

**Comment by johndatserakis** [comment]
Hey there - sorry you're having trouble with this. 

Honestly I don't use SSR for my projects so I was never sure of SSR support for this component. I made a few changes around 2.0 but nothing to my knowledge that would make SSR support *worse*.

Are you using nuxt.js for your SSR project? Have you tried whitelisting this component in some way during the initialization? Can you provide any more detail of how you're installing this component and your SSR configuration - I'm sorta ignorant on SSR usage so the more detail the better.  Thanks.

**Comment by mikerogerz** [comment]
I don't think it's actually related to the SSR usage.. it happened when changes were made to the build. I looked at the min'd source, and noticed that there are checks built into 2.0.1 to check if it's a browser or on the server.. and starting in 2.1.0 that no longer exists.

Something changed in this commit:
cfa0bc80bef7b9416e64e0d839e025d910a0a05b

**Comment by johndatserakis** [comment]
Hey - yea idk this is a bit strange. Really only one dependency was updated in that commit - `rollup-plugin-vue`. A user over there has a question about ssr support [here](https://github.com/vuejs/rollup-plugin-vue/issues/266), maybe that can help.

Although - one thing I noticed that I took out because I didn't see it being used was the `browser` key in the package.json. I added that back right now and built again and pushed. Will you please update to the latest version of  `vue-programmatic-invisible-google-recaptcha` - `2.1.3` and see if it's working for you now? I have a feeling that could be it. Thank you - let me know.

**Comment by mikerogerz** [comment]
That might be the fix, but now I'm getting other compile-time errors regarding plugins in your .babelrc. My project isn't using Babel 7.*. I'm still on 6.* due to a few outdated 3rd party libraries. Here's what it reports:

`ReferenceError: Unknown plugin "@babel/plugin-transform-runtime"`

I might have to stay at version 2.0.1 of your library until I can get everything in my project upgraded.

**Comment by johndatserakis** [comment]
Hmm darn, I thought we were close! Although yea Babel 6 was released a while ago and may be the main issue here - it's hard to say.

Well, when you update to Babel 7 then maybe you can let us know if it starts working for you? I'll be standing by to hear how it goes. Thanks.

**Comment by mikerogerz** [comment]
There are limitations in my project that won't let me upgrade for quite a
while.. But I'll let you know as soon as I can. Thanks a lot for the help
either way.
