### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by random-webdeveloper** [promosis/vue-programmatic-invisible-google-recaptcha#2]
Module build failed: ReferenceError: Unknown plugin "@babel/plugin-transform-runtime" specified in "../project_root/node_modules/vue-programmatic-invisible-google-recaptcha/.babelrc" at 0, att
empted to resolve relative to ".../project_root/node_modules/vue-programmatic-invisible-google-recaptcha"

(obviously i left out my full user path)

i am using a .bablerc tho.
using babel with verison 6.26.3, so i can't just "npm install @babel/plugin-transform-runtime"
there is only a babel-plugin-transform-runtime for my version, but it is specifically looking for a "@babel/plugin-transform-runtime"

how to resolve this?

**Comment by johndatserakis** [comment]
Hey there - sorry you're having trouble. 

Hmm yea I see what you're saying - let me look into this. Maybe there is something that can allow these two to bridge together. Can I ask - are you using yarn or npm in your project.

**Comment by random-webdeveloper** [comment]
i'm using yarn, does that make a difference?

**Comment by johndatserakis** [comment]
Ok got it. Well the reason I asked is because I think yarn has some feature that will basically override a dependency for you - I think it was something like a `resolutions` property.

I'm not sure though, so let me research this a bit.

If that doesn't work I can look into removing the polyfill from the build and force users to install it themselves either through npm in the build or by using a cdn. Maybe that's how I should have it set up in the first place. What do you think.

**Comment by johndatserakis** [comment]
Also - could you try this `npm i -D @babel/plugin-transform-runtime`. I know it's weird because you are using the other version, but at the very least it may make the component behave correctly in your environment. Figured it's worth a shot.

**Comment by random-webdeveloper** [comment]
`npm i -D @babel/plugin-transform-runtime` doesn't work for me, same error as before.
Yeah I guess making users install the polyfill separately is the better choice here, if the user wanted to use polyfills, he would install it anyway, for the rest of his code. If he does not, and wants to reduce bundle size, he just doesn't add the polyfill. Seems reasonable to me.

**Comment by johndatserakis** [comment]
Ok yea - I've done that with other projects but for whatever reason I initialized this one here differently. I'll get it switched over - sorry for the wait I'm just tied up at the moment, maybe in like another day or two or earlier I'll have it done. I'll post here when complete. Thank you.

**Comment by random-webdeveloper** [comment]
No problem, no need to rush :D

**Comment by johndatserakis** [comment]
Hey bud so I've put a few hours into it this afternoon,  and I'm a bit stumped. 

I was a bit off in my other response - it turns out I was thinking about the wrong thing and this project doesn't require the polyfill I thought it did. The `@babel/plugin-transform-runtime` is there only for the dev/build process and shouldn't be coming up in your usage.

Now that I step back and look at your problem I have one question for myself - why is your app looking at this component's .babelrc? That's weird, and I think whatever answers this question will lead us to our solution. It should only be looking in the `dist` folder for the actual compiled code.

In my time developing open source stuff I've never had someone mention this issue - and there are all types of builds and different usages - even people using it straight from the browser cdn.

Because I'm applying babel when I build my component, that means that you shouldn't need to build it any further - you just need to `import` or `require` it your app and you should be good. It should not be looking at the component's `.babelrc` at all from what I understand. Unless - your build environment is sorta custom and you're telling it to look at this component specifically - and if that's the case I would tell it to skip this component.

Can you show me in your code how you're importing the component, how you're using it, and what your build process looks like? Also what version is in your package-lock.json and your package.json?

I'm here to help - sorry this is turning out to be more complicated then anticipated!

**Comment by johndatserakis** [comment]
Hey there - I just wanted to follow up on my recent comment - did it help lead you to anything?

**Comment by random-webdeveloper** [comment]
Hi! sorry dude, I completely missed your answer :/ I will look into that in the next few days and will try to give you a better answer when I have time 
Thank you very much for your engagement tho

**Comment by random-webdeveloper** [comment]
So, finally I found some time to give you an answer.
If I use your package with your provided `<script src="https://unpkg.com/vue-programmatic-invisible-google-recaptcha@2.1.3/dist/vue-programmatic-invisible-google-recaptcha.min.js"></script>`
everything works perfectly, but if i use it like
```
import VueProgrammaticInvisibleGoogleRecaptcha from 'vue-programmatic-invisible-google-recaptcha';
Vue.component('vue-programmatic-invisible-google-recaptcha', VueProgrammaticInvisibleGoogleRecaptcha);
```
with the newest version of this package (installed via NPM or yarn doesn't make a difference here) I get
Module build failed: ReferenceError: Unknown plugin "@babel/plugin-transform-runtime" specified in "/Users/username/Sites/project/node_modules/vue-programmatic-invisible-google-recaptcha/.babe
lrc" at 0, attempted to resolve relative to "/Users/username/Sites/project/node_modules/vue-programmatic-invisible-google-recaptcha"
    at /Users/username/Sites/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17

in my package.json under "devDependencies" it states `"vue-programmatic-invisible-google-recaptcha": "^2.1.3",` but it gives me the same error when in dependencies and not devDependencies. Same goes for yarn.

I don't really understand what you mean with "build process" to be honest, I'm using webpack in laravel with a VUE SPA as frontend, if that helps you.

**Comment by johndatserakis** [comment]
Hmm yea this is strange, at least you can get it to work by directly importing the browser version for now.

Something is up here but I just won't be able to get a better idea unless I can look through some code and dig around. I'm sure the project you're working on is private, but if you every get around to making an example repo with this issue happening I'd be more than willing to take a look and try and figure it out

It's just one of those things where there's so many variables I'll have to actually look at the code. Thanks, and sorry for the trouble.

**Comment by bmpf** [comment]
I got the same error. 
Still no answer ?
